version: "3"

services:
  shareyourcloning:
    build: .
    image: shareyourcloning
    ports:
      - "8000:8000"
    volumes:
      #config.json maps in this directory maps to /frontend/config.json
      - ./config.json:/home/backend/frontend/config.json
